/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
import * as i0 from "@angular/core";
import * as i1 from "./ngx-pica.module";
import * as i2 from "./ngx-pica-exif.service";
import * as i3 from "./ngx-pica.service";
import * as i4 from "./ngx-pica-image.service";
var NgxPicaModuleNgFactory = i0.ɵcmf(i1.NgxPicaModule, [], function (_l) { return i0.ɵmod([i0.ɵmpd(512, i0.ComponentFactoryResolver, i0.ɵCodegenComponentFactoryResolver, [[8, []], [3, i0.ComponentFactoryResolver], i0.NgModuleRef]), i0.ɵmpd(4608, i2.NgxPicaExifService, i2.NgxPicaExifService, []), i0.ɵmpd(4608, i3.NgxPicaService, i3.NgxPicaService, [i2.NgxPicaExifService]), i0.ɵmpd(4608, i4.NgxPicaImageService, i4.NgxPicaImageService, []), i0.ɵmpd(512, i1.NgxPicaModule, i1.NgxPicaModule, [])]); });
export { NgxPicaModuleNgFactory as NgxPicaModuleNgFactory };
//# sourceMappingURL=ngx-pica.module.ngfactory.js.map